modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="meme_dimension_mod"
version="1.0.0"
displayName="Meme Dimension Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.youtube.com/NoahB"
authors="NoahB"

[[dependencies.meme_dimension_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




